server:
  port: 1111
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: 
    url: jdbc:h2:mem:testdb
    username: sa
     
  mvc:
    view:
      prefix: /view/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 465
    username: rahul25ray1998@gmail.com
    password: barshara
    properties.mail.smtp:
                      auth: true
                      starttls:
                        enable: true
 
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect     